//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using LibraryManagement.ViewModel;
    using LibraryManagement.ViewModel.Validator;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DocGia : ValidatableBindableBase<DocGia>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();

            List<string> emptyList = new List<string>();
            _errors[nameof(Ten)] = emptyList;
            _errors[nameof(DiaChi)] = emptyList;
            _errors[nameof(Email)] = emptyList;
        }

        static DocGia()
        {
            validator = new ReaderValidator();
        }
        private static int firstId = DataProvider.Instance.DataBase.LoaiDocGias.First().Id;
        private string _ten;
        private int _idLoai;
        private DateTime _ngaySinh = DateTime.Now.AddYears(-18);
        private string _diachi;
        private string _email;
        private DateTime _ngayLap = DateTime.Now;

        public int Id { get; set; } = firstId;

        public string Ten
        {
            get { return _ten; }
            set { SetValidatableProperty(ref _ten, value, this); }
        }
        public int IdLoai
        {
            get { return _idLoai; }
            set { SetBindableProperty(ref _idLoai, value); }
        }
        public DateTime NgaySinh
        {
            get { return _ngaySinh; }
            set
            {
                SetValidatableProperty(ref _ngaySinh, value, this);
                RaiseErrorChangedOnProperty("NgayLap", this);
            }
        }
        public string DiaChi
        {
            get { return _diachi; }
            set { SetValidatableProperty(ref _diachi, value, this); }
        }
        public string Email
        {
            get { return _email; }
            set { SetValidatableProperty(ref _email, value, this); }
        }
        public DateTime NgayLap
        {
            get { return _ngayLap; }
            set
            {
                SetValidatableProperty(ref _ngayLap, value, this);
                RaiseErrorChangedOnProperty("NgaySinh", this);
            }
        }

        public Nullable<bool> IsDeleted { get; set; }


        

        public virtual LoaiDocGia LoaiDocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
