//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using LibraryManagement.ViewModel;
    using LibraryManagement.ViewModel.Validator;
    using System;
    using System.Collections.Generic;

    public partial class DocGia : ValidatableBindableBase<DocGia>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }

        static DocGia()
        {
            validator = new ReaderValidator();
        }

        private string _ten;

        public int Id { get; set; }

        public string Ten
        {
            get { return _ten; }
            set { SetValidatableProperty(ref _ten, value, this); }
        }
        public Nullable<int> IdLoai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }

        public virtual LoaiDocGia LoaiDocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
